/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.adidas.product.worker.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class WorkerFailure extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5738569331385980296L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WorkerFailure\",\"namespace\":\"com.adidas.product.worker.schema\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"consumer\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"millis\",\"type\":\"long\"},{\"name\":\"exception\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"stacktrace\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<WorkerFailure> ENCODER =
      new BinaryMessageEncoder<WorkerFailure>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<WorkerFailure> DECODER =
      new BinaryMessageDecoder<WorkerFailure>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<WorkerFailure> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<WorkerFailure> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<WorkerFailure>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this WorkerFailure to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a WorkerFailure from a ByteBuffer. */
  public static WorkerFailure fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String id;
   private java.lang.String consumer;
   private long millis;
   private java.lang.String exception;
   private java.lang.String stacktrace;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WorkerFailure() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param consumer The new value for consumer
   * @param millis The new value for millis
   * @param exception The new value for exception
   * @param stacktrace The new value for stacktrace
   */
  public WorkerFailure(java.lang.String id, java.lang.String consumer, java.lang.Long millis, java.lang.String exception, java.lang.String stacktrace) {
    this.id = id;
    this.consumer = consumer;
    this.millis = millis;
    this.exception = exception;
    this.stacktrace = stacktrace;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return consumer;
    case 2: return millis;
    case 3: return exception;
    case 4: return stacktrace;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.String)value$; break;
    case 1: consumer = (java.lang.String)value$; break;
    case 2: millis = (java.lang.Long)value$; break;
    case 3: exception = (java.lang.String)value$; break;
    case 4: stacktrace = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'consumer' field.
   * @return The value of the 'consumer' field.
   */
  public java.lang.String getConsumer() {
    return consumer;
  }

  /**
   * Sets the value of the 'consumer' field.
   * @param value the value to set.
   */
  public void setConsumer(java.lang.String value) {
    this.consumer = value;
  }

  /**
   * Gets the value of the 'millis' field.
   * @return The value of the 'millis' field.
   */
  public java.lang.Long getMillis() {
    return millis;
  }

  /**
   * Sets the value of the 'millis' field.
   * @param value the value to set.
   */
  public void setMillis(java.lang.Long value) {
    this.millis = value;
  }

  /**
   * Gets the value of the 'exception' field.
   * @return The value of the 'exception' field.
   */
  public java.lang.String getException() {
    return exception;
  }

  /**
   * Sets the value of the 'exception' field.
   * @param value the value to set.
   */
  public void setException(java.lang.String value) {
    this.exception = value;
  }

  /**
   * Gets the value of the 'stacktrace' field.
   * @return The value of the 'stacktrace' field.
   */
  public java.lang.String getStacktrace() {
    return stacktrace;
  }

  /**
   * Sets the value of the 'stacktrace' field.
   * @param value the value to set.
   */
  public void setStacktrace(java.lang.String value) {
    this.stacktrace = value;
  }

  /**
   * Creates a new WorkerFailure RecordBuilder.
   * @return A new WorkerFailure RecordBuilder
   */
  public static com.adidas.product.worker.schema.WorkerFailure.Builder newBuilder() {
    return new com.adidas.product.worker.schema.WorkerFailure.Builder();
  }

  /**
   * Creates a new WorkerFailure RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new WorkerFailure RecordBuilder
   */
  public static com.adidas.product.worker.schema.WorkerFailure.Builder newBuilder(com.adidas.product.worker.schema.WorkerFailure.Builder other) {
    return new com.adidas.product.worker.schema.WorkerFailure.Builder(other);
  }

  /**
   * Creates a new WorkerFailure RecordBuilder by copying an existing WorkerFailure instance.
   * @param other The existing instance to copy.
   * @return A new WorkerFailure RecordBuilder
   */
  public static com.adidas.product.worker.schema.WorkerFailure.Builder newBuilder(com.adidas.product.worker.schema.WorkerFailure other) {
    return new com.adidas.product.worker.schema.WorkerFailure.Builder(other);
  }

  /**
   * RecordBuilder for WorkerFailure instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WorkerFailure>
    implements org.apache.avro.data.RecordBuilder<WorkerFailure> {

    private java.lang.String id;
    private java.lang.String consumer;
    private long millis;
    private java.lang.String exception;
    private java.lang.String stacktrace;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.adidas.product.worker.schema.WorkerFailure.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.consumer)) {
        this.consumer = data().deepCopy(fields()[1].schema(), other.consumer);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.millis)) {
        this.millis = data().deepCopy(fields()[2].schema(), other.millis);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.exception)) {
        this.exception = data().deepCopy(fields()[3].schema(), other.exception);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.stacktrace)) {
        this.stacktrace = data().deepCopy(fields()[4].schema(), other.stacktrace);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing WorkerFailure instance
     * @param other The existing instance to copy.
     */
    private Builder(com.adidas.product.worker.schema.WorkerFailure other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.consumer)) {
        this.consumer = data().deepCopy(fields()[1].schema(), other.consumer);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.millis)) {
        this.millis = data().deepCopy(fields()[2].schema(), other.millis);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.exception)) {
        this.exception = data().deepCopy(fields()[3].schema(), other.exception);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.stacktrace)) {
        this.stacktrace = data().deepCopy(fields()[4].schema(), other.stacktrace);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.adidas.product.worker.schema.WorkerFailure.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.adidas.product.worker.schema.WorkerFailure.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'consumer' field.
      * @return The value.
      */
    public java.lang.String getConsumer() {
      return consumer;
    }

    /**
      * Sets the value of the 'consumer' field.
      * @param value The value of 'consumer'.
      * @return This builder.
      */
    public com.adidas.product.worker.schema.WorkerFailure.Builder setConsumer(java.lang.String value) {
      validate(fields()[1], value);
      this.consumer = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'consumer' field has been set.
      * @return True if the 'consumer' field has been set, false otherwise.
      */
    public boolean hasConsumer() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'consumer' field.
      * @return This builder.
      */
    public com.adidas.product.worker.schema.WorkerFailure.Builder clearConsumer() {
      consumer = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'millis' field.
      * @return The value.
      */
    public java.lang.Long getMillis() {
      return millis;
    }

    /**
      * Sets the value of the 'millis' field.
      * @param value The value of 'millis'.
      * @return This builder.
      */
    public com.adidas.product.worker.schema.WorkerFailure.Builder setMillis(long value) {
      validate(fields()[2], value);
      this.millis = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'millis' field has been set.
      * @return True if the 'millis' field has been set, false otherwise.
      */
    public boolean hasMillis() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'millis' field.
      * @return This builder.
      */
    public com.adidas.product.worker.schema.WorkerFailure.Builder clearMillis() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'exception' field.
      * @return The value.
      */
    public java.lang.String getException() {
      return exception;
    }

    /**
      * Sets the value of the 'exception' field.
      * @param value The value of 'exception'.
      * @return This builder.
      */
    public com.adidas.product.worker.schema.WorkerFailure.Builder setException(java.lang.String value) {
      validate(fields()[3], value);
      this.exception = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'exception' field has been set.
      * @return True if the 'exception' field has been set, false otherwise.
      */
    public boolean hasException() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'exception' field.
      * @return This builder.
      */
    public com.adidas.product.worker.schema.WorkerFailure.Builder clearException() {
      exception = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'stacktrace' field.
      * @return The value.
      */
    public java.lang.String getStacktrace() {
      return stacktrace;
    }

    /**
      * Sets the value of the 'stacktrace' field.
      * @param value The value of 'stacktrace'.
      * @return This builder.
      */
    public com.adidas.product.worker.schema.WorkerFailure.Builder setStacktrace(java.lang.String value) {
      validate(fields()[4], value);
      this.stacktrace = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'stacktrace' field has been set.
      * @return True if the 'stacktrace' field has been set, false otherwise.
      */
    public boolean hasStacktrace() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'stacktrace' field.
      * @return This builder.
      */
    public com.adidas.product.worker.schema.WorkerFailure.Builder clearStacktrace() {
      stacktrace = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public WorkerFailure build() {
      try {
        WorkerFailure record = new WorkerFailure();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.consumer = fieldSetFlags()[1] ? this.consumer : (java.lang.String) defaultValue(fields()[1]);
        record.millis = fieldSetFlags()[2] ? this.millis : (java.lang.Long) defaultValue(fields()[2]);
        record.exception = fieldSetFlags()[3] ? this.exception : (java.lang.String) defaultValue(fields()[3]);
        record.stacktrace = fieldSetFlags()[4] ? this.stacktrace : (java.lang.String) defaultValue(fields()[4]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<WorkerFailure>
    WRITER$ = (org.apache.avro.io.DatumWriter<WorkerFailure>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<WorkerFailure>
    READER$ = (org.apache.avro.io.DatumReader<WorkerFailure>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
